version: "3"
services:
  node:
    build: .
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "${API_PORT}:${API_PORT}"
    command: "npm start"
    links:
      - database:postgres

  database:
    image: "postgres"
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PORT: 5432
    volumes:
      - luxelare-notes-db-data:/var/lib/postgresql/data

volumes:
  luxelare-notes-db-data: